############# English navigation ##############

# main menu
#[[main]]
#name = "Home"
#url = "/"
#weight = 1

#[[main]]
#name = "Categories"
#url = "/categories"
#weight = 2

[[main]]
weight = 2
name = "Articles"
url = "/blog"

[[main]]
weight = 3
name = "Contributors"
url = "/authors"

[[main]]
weight = 4
name = "Events"
url = "/events"

[[main]]
weight = 5
name = "Hugoplate Examples"

# ---------

[[main]]
parent = "Hugoplate Examples"
name = "About"
url = "/about"

[[main]]
parent = "Hugoplate Examples"
name = "Elements"
url = "/elements"

[[main]]
parent = "Hugoplate Examples"
name = "Contact"
url = "/contact"

[[main]]
parent = "Hugoplate Examples"
name = "404 Page"
url = "/404"


# Footer menu ------------------------------------------------------------------

[[footer]]
name = "About"
url = "/about"
weight = 1


#[[footer]]
#name = "Elements"
#url = "/elements"
#weight = 2

#[[footer]]
#name = "Privacy Policy"
#url = "/privacy-policy"
#weight = 3
